### ISSUE TITLE
Missing space character

### ISSUE THREAD

**Issue by marcus-herrmann** [stefanjudis/stefan-judis-website#2]
See: https://github.com/stefanjudis/stefan-judis-website/blob/master/components/Person.vue#L38

At the end of the nuxt-link, before the "and". Should be:
```
 <nuxt-link to="/today-I-learned/">my web dev learnings constantly</nuxt-link> and write
```

**Comment by stefanjudis** [comment]
Hah! thanks! fixded (deploy is running)
